### ISSUE TITLE
Figure out the default privacy boundary for the web

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#1]
The [origin](https://html.spec.whatwg.org/multipage/origin.html#origin) is the default _security_ boundary for the web. That is, different things within the same origin are expected to be able to interfere with each other, while cross-origin things have to opt into communication. There are some exceptions, like cookies and [Chrome's site isolation](http://www.chromium.org/Home/chromium-security/site-isolation#TOC-Current-Status), but we have consensus that origin isolation is the goal.

A default privacy boundary would, roughly, be the point at which the user (rather than the page) needs to approve communication.

We're currently defaulting to the [Public Suffix List](https://publicsuffix.org/) for this, but that answer isn't working perfectly. Specifically, the PSL groups origins into sites, and we declare that the site is the privacy boundary. The PSL has known [problems](https://github.com/sleevi/psl-problems), and it's not currently funded well enough to handle wider adoption, especially in [potentially-adversarial situations](https://github.com/privacycg/private-click-measurement/issues/78). We might be able to round up the needed extra investment if we so choose.

A [variant of First Party Sets](https://github.com/privacycg/first-party-sets#origins-instead-of-registrable-domains) might be able to serve as an alternate default privacy boundary.

**Comment by jyasskin** [comment]
I forgot to mention that the IETF has tried to address an adjacent problem, but didn't succeed: https://datatracker.ietf.org/wg/dbound/about/ and https://github.com/equalsJeffH/dbound#readme.

**Comment by torgo** [comment]
As discussed today - we think building on the [whatwg def](https://html.spec.whatwg.org/multipage/origin.html#origin) of origin and writing some words around that might be the best approach here. We could write it from the perspective of how new technologies should behave.

**Comment by jyasskin** [comment]
Looking at the [discussion](https://github.com/w3ctag/privacy-principles/blob/main/meetings/2021-07-07-minutes.md#figure-out-the-default-privacy-boundary-for-the-web), I think we have some ambiguity about what "use the origin for the default privacy boundary" would mean. For example, @darobin said ["Any company that can acquire many companies and put them under its domain can freely share data"](https://github.com/w3ctag/privacy-principles/blob/main/meetings/2021-07-07-minutes.md#:~:text=Any%20company%20that%20can%20acquire%20many%20companies%20and%20pt%20them%20under%20its%20domain%20can%20freely%20share%20data). To make this concrete, say the company owns `bigcompany.com`. If the **origin** is the privacy boundary, the company would have to put the acquired companies at `https://bigcompany.com/acquired1`, `https://bigcompany.com/acquired2`, etc., in order to avoid asking the user each time they want to share data. This is a security problem, because now any vulnerability in acquiredN can see and interfere with all the data for all the pieces of BigCo. There's some mention of creating sub-origin security boundaries in the notes, but we should check with WebAppSec before assuming that's plausible. It's also a big migration, and one that I don't see a plausible way to finish (see #21).

As @hober said, ["The default privacy boundary in terms of deployed content is the **site** not the origin."](https://github.com/w3ctag/privacy-principles/blob/main/meetings/2021-07-07-minutes.md#:~:text=The%20default%20privacy%20boundary%20in%20terms%20of%20deployed%20content%20is%20the%20site%20not%20the%20origin), where "site" is defined using the Public Suffix List. That is, BigCo could put its acquisitions at `https://acquired1.bigcompany.com/`, `https://acquired2.bigcompany.com/`, etc., putting each on its own [origin](https://html.spec.whatwg.org/multipage/origin.html#origin), which puts a security boundary between each but still allows them to communicate without asking the user. The privacy domain still builds on origins, but it includes more than one of them.

**Comment by darobin** [comment]
My suggestion from the meeting discussion:

* We define when we see it as important to have a privacy boundary in a principled, even if we can't enforce it technically.
* We encourage enforcing it technically where possible, and suggest a hand-off to policymakers for what we cannot enforce, with the hope that they use similar principles.
* We admit that perfection is not required. You can write a scam with access to nothing more than a `p` element, which means that security is never perfect either.

**Comment by dmarti** [comment]
Possibly related: what does a user understand as a single "thing" they are interacting with? https://github.com/w3ctag/privacy-principles/pull/44

**Comment by darobin** [comment]
This feels overtaken by events and captured by the rest of the document.
