### ISSUE TITLE
Reciprocal duty of honesty for publishers

### ISSUE THREAD

**Issue by jbradleychen** [w3ctag/privacy-principles#108]
When a user is a publisher, what duty does the user have to be honest about their public acts? _Publisher_ should be understood broadly to include individuals who act in public. In particular this should include publishers of software.

Users make trust decisions based on the context information available from publishers. Given the essential role of good trust decisions by the public in public safety, what rights should the public have to meaningful reputation and other context information for publishers? Is it okay for a publisher to actively avoid accumulating reputation, such that prior good or bad work is dissociated from the publisher's reputation? How do we support the privacy rights of publishers without forfeiting the public's right to safety?

**Comment by npdoty** [comment]
As noted in #107, the task force's conclusions have been to design APIs to avoid making assertions about/on the user's behalf and that this document does not effectively put requirements on individual people.

The concept of user as publisher may also be connected to two other privacy principles, where privacy includes freedom from intrusion and unwanted information -- [Harassment](https://w3ctag.github.io/privacy-principles/#harassment) and [Unwanted Information](https://w3ctag.github.io/privacy-principles/#unwanted-information). Those sections include some potential mitigations, including controlling the presentation of information and building reputation, trust and reporting based on relationships.

Providing functionality to address other societal impacts of published content, for example misinformation, seems of interest to many (e.g. it's [included in Ethical Web Principles](https://w3ctag.github.io/ethical-web-principles/#verify)) but likely will not be comprehensively addressed in Privacy Principles.

**Comment by npdoty** [comment]
closing per task force discussions
