### ISSUE TITLE
Endorse logged-out website use

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#120]
The ability to generally use websites without logging in is valuable and increases privacy, both because usernames and account-recovery mechanisms are identifying, and because login tends to give away email addresses which allow sites to spam users. I think we could write a principle to that effect, but I'm worried that it'll be interpreted as endorsing some practices that this group wouldn't want to implicitly endorse. For example:

* Sites fund themselves by showing ads instead of having people subscribe, and personalization makes those ads pay more or be available at all.
* Sites use IP addresses and fingerprinting to enforce limits on the number of free articles people can see, and to figure out how many people are reading their things.

We could write the principle anyway, and let people balance the resulting conflicts themselves, or we could try to include some help with the tradeoffs.

**Comment by dmarti** [comment]
I share your concern about implicitly endorsing problematic practices.

In most real situations, the choice won't be between logging in and a data-collection-free web session -- it will be between logging in (which the user can understand and should be made clear to them) and some kind of harder-to-understand data collection.
