### ISSUE TITLE
Discuss aggregate statistics about site users

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#121]
Sites often want to know how many people are reading which articles, or other aggregate information about their audiences. This is fairly benign when it's just a total number of users over the whole site, but it can become harmful when it starts letting advertisers on the site target to just the demographic that does or doesn't visit the site.

Collecting aggregate statistics also implies that the site can distinguish different people and learn some of their characteristics, which is currently accomplished by attaching those characteristics to individual identified people. There's hope that it'll be possible to do this more-privately in the long run.

We can help motivate other groups to develop the more-private mechanisms if we identify what kinds of aggregate statistics are ok and what kinds aren't.

**Comment by darobin** [comment]
Needs @jyasskin.

**Comment by npdoty** [comment]
https://w3ctag.github.io/privacy-principles/#ancillary-uses includes text now on aggregation, why it might be more acceptable, and notes about where ongoing work is happening
