### ISSUE TITLE
Privacy rules can be overridden with a really good reason

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#137]
As described in https://w3ctag.github.io/privacy-principles/#how-this-document-fits-in, other ethical principles can override privacy principles. #73 and #105 discuss anti-abuse reasons to override privacy principles, but we also have at least journalistic purposes in the public interest.

This comes from the March 2 brainstorm:
https://github.com/w3ctag/privacy-principles/blob/1876fd06828edb8dd6411fbddc1d3da254833bd4/meetings/2022-03-02-minutes.md?plain=1#L30-L49

**Comment by wseltzer** [comment]
My phrasing in the discussion was shaded in the opposite direction: privacy isn't absolute, but requests for exception must cite strong reasons in order to be considered. The default should very strongly lean toward privacy.

**Comment by torgo** [comment]
We think this is already addressed.
