### ISSUE TITLE
making notifications/interruptions guidance more general

### ISSUE THREAD

**Issue by npdoty** [w3ctag/privacy-principles#151]
We might want to be less specific about the particular UI or the particular notifications features.

For example, UAs also make decisions about blocking pop-ups, alert dialogs, PWA installation prompts, etc.

Permissions should certainly always be revocable but that might be enabled on a particular notification rather than an audit UI, etc.

Principle should provide guidance not just for the Notifications API but for interruptive technology more generally.

**Comment by torgo** [comment]
Agreed to close this on the basis of https://github.com/w3ctag/privacy-principles/pull/132.

**Comment by npdoty** [comment]
Current text seems to cover Notifications API, but also other kinds of interruptions: https://w3ctag.github.io/privacy-principles/#interruptions

Provides guidance to UAs and to sites. It's possible we could still expand with examples of other types of interruptions, but seems good enough for the time being.
