### ISSUE TITLE
Clarify "party that controls this origin or site" to cover the control of data

### ISSUE THREAD

**Issue by dmarti** [w3ctag/privacy-principles#152]
In the section on [Server-Side Parties](https://w3ctag.github.io/privacy-principles/#parties) we have:

> The [party](https://w3ctag.github.io/privacy-principles/#dfn-party) that controls this [origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin) or [site](https://html.spec.whatwg.org/multipage/origin.html#site) is known as the web page's first party.

Can we clarify that the "control" covered here is control of how information on a person's interaction with a site is used, and not other levels of control?

For example, a site might host blog content from a variety of bloggers who "control" the text on the page, and the site might be hosted on a VPS provider that has "control" over the hardware on which the site runs -- but the "control" that we want to cover here is who has control over access to data on how people use the site.

**Comment by torgo** [comment]
Closed on basis of #213.

**Comment by jyasskin** [comment]
To be clear, #213's reference is that it **didn't** do anything about this issue. Up to @dmarti whether to reopen.
