### ISSUE TITLE
2.4 right to know who has data about you

### ISSUE THREAD

**Issue by IreneKnapp** [w3ctag/privacy-principles#156]
It is unclear to me to what extent this spec is attempting to be aspirational vs. descriptive. A major gap in GDPR and analogous laws right now is that, in many situations, data subjects have no well-defined way to discover which corporations or other entities hold data about them, and thus have no way to issue deletion or transparency requests.

If the spec is meant to include rights which don't exist today but should, I think it would be very valuable to include something in the enumeration of data rights in 2.4, to the effect that data subjects have a right to be informed that someone has data about them.

This idea came up during a Twitter conversation, and I'm writing this issue in an attempt to capture the thought. Please feel free to ask clarifying questions and I'll try to elaborate. I also take no strong position on exactly what form the proposed right should take; I'm just trying to flag a gap that I see in what's there now.

**Comment by npdoty** [comment]
I don't think we need to be bound by the exact details of legal rights of different jurisdictions for this document, although we did start by trying to draw from established laws and sets of principles. But we do want to enumerate rights for which we think there can be a community consensus.

Access is one well-established right, and as part of that I tried to expand the concept to include discovery: that a person should be able to find out who has what information about them, that there aren't secret databases of information about you which you would have no capability to review or correct, etc. I agree that it's not super clear how well GDPR actually effectuates that capability. And it wouldn't be the easiest thing to implement technically, but I think it is a meaningful right that we could acknowledge and subsequently work to make real.

Is that what you mean by a right to know? Or is there something more affirmative where people should be directly notified about data that is collected somewhere about them?

**Comment by IreneKnapp** [comment]
Thanks! Yes, your "discovery" idea seems sufficient to me. The direct notification would be only one specific way of making that possible, not the only way. I looked again at the draft and the "right to access" as currently written doesn't seem to imply that to me; the wording is ambiguous enough that I think most people would take it to just mean the same thing that GDPR requires. So perhaps the bug is to make sure the intention is clear. :)

**Comment by torgo** [comment]
Closing on the basis of merging of #219.
