### ISSUE TITLE
cite finding on unsanctioned tracking 

### ISSUE THREAD

**Issue by npdoty** [w3ctag/privacy-principles#160]
This seems like important prior art to consider explicitly: https://www.w3.org/2001/tag/doc/unsanctioned-tracking/

1. cite in the identity on the web / cross-site tracking
2. note affordances of using established mechanisms with potential transparency and control (perhaps in section on transparency, or as part of a strategies #118 section)
3. note limits of technical solutions: responsibility of other parties and need for regulatory protections

**Comment by torgo** [comment]
This is done.
