### ISSUE TITLE
Principle 2.1 (Identity on the Web) should account for users not wishing to share their identity

### ISSUE THREAD

**Issue by kdenhartog** [w3ctag/privacy-principles#163]
Looking at the way the principle is defined currently creates a good foundation for accurately reflecting how identity on the web works today. However, it doesn't accurately reflect many users (myself included) on the web goal where if I choose to not share any aspect of my identity I should be able to do so. I think this principle should be updated to account for when the user chooses not to share any information even in a first party context. While this isn't necessarily perfectly possible on the web today (e.g. any time you make a web request you're probably sharing an IP address), I think it's a good north star that would be a good thing to include as a foundational principle on the web that we aim to achieve.

To reconcile this position with the common tension that web services typically require additional information in order to legitimately provide their service (e.g. needing location information for regulatory requirements) we should also account for the fact that the user is entering in a negotiation of sorts where they're trading their information in exchange for access and usage of services on the web. This should be done through a consent based approach that shouldn't assume that bundles of attributes (e.g. the identity of the user) need to all be shared at the same time and instead the information can be gradually shared as the user wants to grant more information to the service. 

This model of information sharing most accurately reflects what we as people are used to in meatspace where walking in a public space I generally assume that a researcher sitting in the public space can gather information about my physical attributes like what I'm wearing or can take a photo of me. However, the researcher must ask me for each one of my attributes such as name or date of birth in order to gather that information. They can't inherently infer this easily just based on my appearance (let's leave the celebrity edge case out of this analogy for now). This is similar to on the web the web service can gather information about my location based on my IP address today, but the user can make attempts to hide it such as via a proxy or VPN service. The difference is that on the web we have a greater granularity of the information we reveal as we access services on the web and therefore have a greater ability to reveal less unless we (as users) explicitly consent to sharing this information in exchange for a greater amount of access to services on the web.

**Comment by jyasskin** [comment]
https://w3ctag.github.io/privacy-principles/#dfn-identity was meant to indicate that people can decide what characteristics they present to any context they're interacting with, all the way down to not sharing any characteristics ... but we probably need a note to make that more clear.

https://w3ctag.github.io/privacy-principles/#principle-identity-per-context also meant to emphasize that it should be up to the user what identity they present to a site, which can include an identity that isn't connected to any physical-world identity or the identity presented to any other site, and here also, the fact that you didn't get that meaning means we need to clarify it somehow.

If you have ideas for the right clarifying text, I'd love to see them, but if not, we'll try to improve it anyway.

**Comment by kdenhartog** [comment]
Yeah I'll work on a PR this week to improve on this text with some ideas and tag you as a reviewer of it

**Comment by npdoty** [comment]
#191 may address this, @pes10k to review

**Comment by kdenhartog** [comment]
I think #191 in combination with the changes in #166 (to further clarify what "living in obscurity" can look like in the context of a UA) would definitely close this one

**Comment by pes10k** [comment]
terrific @kdenhartog , thanks! Will close this
