### ISSUE TITLE
Please don't put cookie consent pop-ups on steroids with this

### ISSUE THREAD

**Issue by cimpok** [w3ctag/privacy-principles#164]
All the people I know are very much annoyed of the plethora of cookie consent questions while browsing. Most of these visitors are simply clicking on the 'recommended' option that most likely makes the annoying pop-up go away immediately with less/no additional clicks. They all have learned that this is usually the 'Yes' option ie. consent-to-all-cookies that gets rid of the annoyance the fastest. This silly cookie-law is one of the worst things that has happened to the internet (social media was the other), it has helped nothing with the privacy but made the browsing more irritating. Please do not put this nonsense on steroids with your new privacy principles.

My proposal:
Please consider the user to be legally mature enough to to make a decision about his privacy data for any set of web sites, for any time period in advance.
In all compliant browsers the user should be able to preset the browsing behavior: what information the user wishes to share in all future browsing sessions. Make a standard for the negotiation about the shared privacy data happen automatically between the browser and all complying websites, and please get rid of asking the same questions many times a day: do I want the cookies of buythisthing.com and then asking the same again on buythatthing.com. Why would I want it any differently?  (for those 0.01% who do, let them set it in a menu, but no more pop-ups for the rest of us please)

So please let us just preset the allow/deny/don't care all of these privacy settings FOR A LIFETIME in our browsers, and don't ask again till we change it.

If I am legally mature enough to make serious decisions, e.g. marry a woman, sell a house, or donate all my bank account to a charity and bear the consequences of this single decision for a lifetime, why I am treated not this way while browsing and forced to answer the same question dozens of times each day?

**Comment by jyasskin** [comment]
This is already discussed in https://w3ctag.github.io/privacy-principles/#opt-in-out, where we've endorsed the idea of  global opt-outs and expressed skepticism at the value of frequent consent prompts. It's difficult in practice to actually standardize consent like this: the exact question tends to differ by legal jurisdiction and website, which makes it hard to encode it into browser UI. And of course, that's why you get asked over and over again: not because anyone thinks you're incapable of deciding the answer once and having it apply for a [long time](https://twitter.com/gabrielazanfir/status/1524512259581558787), but because it's just hard to ensure you've answered the same question that the next site wants to ask.

I'd also like to caution you to follow the [W3C code of conduct](https://www.w3.org/Consortium/cepc/). In particular, don't denigrate mentally ill people by using them as a shorthand for general badness or incapacity.

**Comment by cimpok** [comment]
Thank you for the reply, I'm sorry for the shorthand, I removed it.

You say it's just hard to ensure I've answered the same question that the next site wants to ask. I thought this is the very place where these new principles* are being born that could ensure that there will not be 748 arbitrary questions on privacy, but let's say, only three standard ones which all could be easily set in advance.

* These principles could serve as a basis for future jurisdictions at some point, but they will be able to educate the questioning habits of websites much sooner.

**Comment by jyasskin** [comment]
The W3C writes voluntary standards, and when it tries to standardize something without first learning enough about the space and designing strong incentives, people just ignore the specification: https://en.wikipedia.org/wiki/Do_Not_Track. I think it's plausible that a working group here could find a relatively standard set of cookie consents (e.g. Functionality, Performance Analysis, and Targeting), but
1) the privacy principles task force that you're talking to isn't that working group and doesn't have the right members to become it, and
2) without laws to enforce that sites obey the preference that the browser reports, there's no reason to think that sites will refrain from showing their own dialogs. Note that the W3C can't directly control what legislators do, and although we could do more to advise them, there's disagreement about whether that would be wise and how best to do it.

There's some hope on the legal front: apparently the [draft European Digital Markets Act](https://www.consilium.europa.eu/media/56086/st08722-xx22.pdf#page=100) restricts some entities from requesting some sorts of consent more than once per year. But even if that text passes, it's not sufficient to make a browser control authoritative, and it doesn't cover even all the common types of cookie consents that I see on the web.

**Comment by cimpok** [comment]
Back then I thought it will take forever for the accessibility features (like image alt attributes, sitemaps, breadcrumbs, etc.) to proliferate into websites, but it happened in a flash when the rumor got out that accessibility would be a significant factor in SEO evaluation. Do_Not_Track is the exact opposite of being a SEO friendly feature :-) so it was doomed.
SEO is the king here, I think in case of any new proposed standard W3C should emphasize its SEO friendliness. And we are lucky with the standardizing of privacy features of websites, it would be no marketing exaggeration at all to present it as super SEO friendly, any standardization is inherently a help for the search engines.

I think legislators would happily endorse a W3C recommendation if it existed, in worst case they would make their own based on W3C's, which would also be a win for all of us.

I did not know about the European Digital Markets Act, thanks, good to see I am not the only one annoyed of being asked the same question a hundred times, sadly it is not a sufficient solution.

**Comment by dmarti** [comment]
A site can follow these principles, and comply with both web standards and the law, without interrupting the user for cookie consent. A good example is this site that we're on right now. See [No cookie for you | The GitHub Blog](https://github.blog/2020-12-17-no-cookie-for-you/)

The current version of the principles already recommends against excessive interruptions for consent. Each search engine sets its own ranking criteria, which is out of scope for this document. But you might want to ask your preferred search engine(s) to rank pages with fewer interruptions such as consent dialogs higher in search results.

**Comment by cimpok** [comment]
Thank you @dmarti for the good example, and thank you GitHub.  (I didn't even notice the good example, I thought I wasn't getting those questions here because I am logged in)
Now W3C and all other policy makers let's do something about that this is not a rare example that a website is proud to point out, but a common thing.

**Comment by dmarti** [comment]
We're closing some already-resolved issues. @cimpok, thank you for bringing this up. If someone has a question about a perceived requirement  for a consent dialog or other UX, please feel free to link here or raise a related issue.

Consent is covered in the current version of the principles, at: https://w3ctag.github.io/privacy-principles/#opt-in-out
