### ISSUE TITLE
Misspelling of "automation"

### ISSUE THREAD

**Issue by puresick** [w3ctag/privacy-principles#169]
Just a small misspelling of "automation" here, which is currently written as "automaton".

https://github.com/w3ctag/privacy-principles/blob/baea91927173412c2452c83264702913f1c16814/index.html#L529

**Comment by puresick** [comment]
I might have been acting to fast on this.

Using "automaton" here makes perfect sense. Since I am not a native english speaker it first looked to me like some misspelling.

**Comment by jyasskin** [comment]
This is a good reminder that we need to simplify the language so non-native English speakers can understand it easily. #15 is related.
