### ISSUE TITLE
Clarify audience & how they engage

### ISSUE THREAD

**Issue by spanicker** [w3ctag/privacy-principles#172]
Explicitly call out primary audiences of this document and how they should engage with the content. eg. spec authors, privacy reviewers.

This will help with formulating the tldr takeaway for each principle, in addition to issue triage and PR reviews.

**Comment by spanicker** [comment]
suggested audiences:

**1. Primary audience**
the tl;dr principles will be targeted towards the following:

- browsers 
- spec writers
- spec reviewers, privacy reviewers

**2. Secondary audience**

- developers building for the web
- policy makers
- any other groups of interest

**Comment by dmarti** [comment]
Journalists (especially reviewers) and authors of tutorials and how-to content for developers and end users?

**Comment by torgo** [comment]
We're closing based on #193.
