### ISSUE TITLE
UAs should support deception principle

### ISSUE THREAD

**Issue by darobin** [w3ctag/privacy-principles#174]
It would be good if browsers helped people lie, for instance enter arbitrary geolocation or use a throwaway ID. @rhiaro had mentioned this as relevant: https://dr.amy.gy/chapter3#computationally-mediated-pro-social-deception

**Comment by samuelweiler** [comment]
Take out TCF (thanks to @dmarti for that suggestion)

**Comment by torgo** [comment]
We're closing it based on #191.
