### ISSUE TITLE
Editorial updates to Identity principle

### ISSUE THREAD

**Issue by rhiaro** [w3ctag/privacy-principles#187]
From @jyasskin in [PR 177](https://github.com/w3ctag/privacy-principles/pull/177#discussion_r978121457):

> I think some of the details here are useful to browser teams deciding what limits to actually enforce. The new text has the positive principle at the top, but you have to scroll through a lot of background to find the [partition](https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/177.html#dfn-partition) boundary that browsers can actually prevent sites from crossing. Maybe it'd be easier to find if we divide the text into ~3 subsections:
>
> 1. Types of recognition
> 2. Browser enforcement
> 3. Something for the "can do the following to help" paragraph...

Logging this feedback for the next editorial pass, as this might be a pattern we can follow in other sections too.

**Comment by jyasskin** [comment]
I was inspired to write #218 while checking that we can close this issue, but I think this is fine even without #218.
