### ISSUE TITLE
Don't ask for fake consent, even if real consent is not required

### ISSUE THREAD

**Issue by dmarti** [w3ctag/privacy-principles#192]
Consent is difficult to obtain and should be asked for rarely.

In some situations, a party can comply with a requirement to get a person to perform some action that is treated as <q>consent</q> without obtaining the person's actual [=consent=].

For example, in some jurisdictions, the law may require "consent' but it would be possible for a party to comply with the law by obtaining "fake consent" (for example, requiring a person to click <q>Yes, I consent</q> in a situation where the person has not been fully informed of what is being consented to.)

What should parties do in a case where these principles do not require getting real consent, but the law requires some action, and will settle for fake consent?

For example, <q>There are some laws that require websites to ask their users' consent to store information even when that information doesn't affect those people's privacy. These laws are harmful.</q> (@jyasskin )

Because requests for consent should be important enough to justify attention from a [=person=], a
[=party=] should avoid distracting the user with attempts to get fake <q>consent</q> in situations
when actual [=consent=] would not be required by these principles.  Responding to unnecessary requests
for consent, real or fake, is unacceptable [=privacy labour=] and limits how much time and attention
a [=person=] can devote to meaningful [=consent=] decisions.

**Comment by jyasskin** [comment]
See also #134.

**Comment by jyasskin** [comment]
@npdoty points to 

> Attempts to obtain consent to [processing](https://w3ctag.github.io/privacy-principles/#dfn-process) that is not in accordance with the person's true preferences result in imposing unwanted [privacy labour](https://w3ctag.github.io/privacy-principles/#dfn-privacy-labor) on the person, and may result in people erroneously giving consent that they regret later.

in [2.12 Consent, Withdrawal of Consent, Opt-Outs, and Objections](https://w3ctag.github.io/privacy-principles/#consent-principles) as possibly addressing this.
