### ISSUE TITLE
Be more explicit about PII-based joins across contexts being bad.

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#194]
I think our [identity-per-context](https://w3ctag.github.io/privacy-principles/#principle-identity-per-context) principle implies that sites shouldn't use personally-identifying information they happen to get to join identities across contexts, and we "support the user's intent to present a directed identity or a site-specific identity".

However, if I were a site that wanted to join data, I could also argue that in the act of giving a site some identifying information, the user has opted into that site using the identity associated with that information, which is likely to be the same identity used by other sites that know the same information.

I think we should explicitly deny that interpretation.

**Comment by jyasskin** [comment]
As Nick suspected, there's already text about this in https://w3ctag.github.io/privacy-principles/#recognition-methods ("collecting the same piece of identifying information on both sites") and in https://w3ctag.github.io/privacy-principles/#user-agent-recognition ("sites must not assume that a person intends to be recognised across different sites simply because they are using the same identifier"), but in #218 I've pulled that up to the paragraphs on [cross-context recognition](https://pr-preview.s3.amazonaws.com/jyasskin/privacy-principles/pull/218.html#dfn-cross-context-recognition).

**Comment by npdoty** [comment]
Thanks, Jeffrey, for looking at this again before I got to it. I think making some of that text explicit in the cross-context recognition is useful. I've added a couple comments to #218 on how exactly to frame it.

**Comment by torgo** [comment]
Closed on the basis of #218.
