### ISSUE TITLE
Address device owners

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#2]
Most of our thinking about stakeholders on the web follows the [priority of constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies): we consider users, authors, implementors, and specifiers. Sometimes we also consider [society](https://w3ctag.github.io/ethical-web-principles/#noharm) or national governments. In https://github.com/w3ctag/design-reviews/issues/606 and other enterprise-focused designs we need to address device owners or administrators, and I haven't been able to find any W3C discussion of how to consider them.

This is a broader question than just the privacy principles we're working on here, but some of the answer belongs here. We should say something about the power dynamics of employees, children, romantic partners, etc. who have to use devices owned by other people who might not always have their best interests in mind, and how the UA is responsible to protect the user while also respecting whatever rights the device owner ought to have.

**Comment by torgo** [comment]
Discussed today. Questions that came up: how do we make this work? What section could we add to the document? How can we tease out something that would be useful for API designers? E.g. The surveillance by abusive partners is real as is the surveillance by corporations over their employees. We should articulate the threat model - how abuses can be mitigated. Should be more detailed.

**Comment by torgo** [comment]
@jyasskin assigned this one to you in absentia but can re-assign if you'd prefer.

**Comment by dmarti** [comment]
The user might consent to some processing of PII while the owner of the device might choose, "not while you're living in my house and using our family's hardware, you're not sharing that"

**Comment by jyasskin** [comment]
We could resolve this pre-FPWD by adding an explicit issue in the document, if we don't find consensus in the next couple weeks.
