### ISSUE TITLE
Missing definitions of [Addressing-Cyber-Harassment] and [Internet-of-Garbage]

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#204]
The uses were added in #195, but we didn't notice that they're not in the `localBiblio`.

This also should have failed our CI: https://github.com/w3c/spec-prod/issues/152.

**Comment by npdoty** [comment]
Apologies, I was a hurry to get that text up to be read and didn't fill in the references. Opened a PR to resolve now.
