### ISSUE TITLE
How idealistic can we be?

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#21]
In the 2021-07-07 minutes, there was an [exchange](https://github.com/w3ctag/privacy-principles/blob/main/meetings/2021-07-07-minutes.md#:~:text=Dan%3A%20from%20the,breaking%20the%20web) between @hober, @torgo, and @jonathanKingston in which Dan suggested that we say "in an ideal world this is the right approach", and hold new proposals to a higher bar than the existing platform. Jonathan pointed out that when this has happened in the past, we've also worked on identifying and fixing the APIs that don't meet the new bar, and Tess pointed out that this takes a concerted effort from important groups.

In the [target privacy threat model](https://w3cping.github.io/privacy-threat-model/#intro:~:text=As%20a%20target,of%20the%20Web.), I addressed this tension by writing that it's "an end state that we hope to migrate to" and that "This is meant to be a plausible threat model: it doesn’t expect to remove any APIs or browser behavior that is deemed essential to the viability of the Web."

I want to try to get consensus from this group that we can only be as idealistic as we can plausibly migrate the rest of the Web to.

**Comment by torgo** [comment]
We discussed today and agreed we need a kind of balance and we will look at each issue individually as we progress. Principles themselves should be idealistic but there are additional factors such as implementability.
