### ISSUE TITLE
Wide Review

### ISSUE THREAD

**Issue by darobin** [w3ctag/privacy-principles#217]
This is a list of who we would like to request wide review from. Please edit this to add to the list.

@torgo:
- [x] The AC and W3C community

@darobin:
- [x] CPPA
- [x] privacy.bm
- [x] EDPB
- [x] ICO
- [x] Consumer Reports
- [ ] noyb

@dmarti:
- [x] IWABG (includes many reps from adtech, IAB Tech Lab, etc.)

@npdoty:
- [x] CDT

@hober:
- [x] Privacy CG

@sandandsnow:
- [x] Ask IAPP to include a news item
- [x] Council of Europe Data Protection / Convention 108
- [x] OECD Working Party on Data Governance and Privacy in the Digital Economy
- [x] [Collaboration on International ICT Policy for East and Southern Africa (CIPESA)](https://cipesa.org/)
- [x] APEC DESG DPS

@samuelweiler:
- [x] EFF
- [x] Wendy
- [x] W3C toot/tweet

**Take your pick!**
- [x] PING
- [x] PATCG
- [ ] digitalclearinghouse.org
- [ ] globalprivacyassembly.org
- [ ] The [Berlin Group](https://www.bfdi.bund.de/EN/Fachthemen/Gremienarbeit/Berlin-Group/Berlin-Group-node.html)
- [ ] appaforum.org
- [ ] [IPEN](https://edps.europa.eu/data-protection/ipen-internet-privacy-engineering-network_en)
- [ ] Privacy International
- [ ] ORG
- [ ] EPIC

**Comment by jyasskin** [comment]
@sandandsnow suggests https://cipesa.org/.

**Comment by npdoty** [comment]
Thanks for getting us started with this list. I have a couple lists/contacts in public interest or consumer advocacy groups. It seems like most of this list is US- and EU-focused, though, so we might try to identify or ask for help in reaching organizations located in other parts of the world.

**Comment by darobin** [comment]
Yes, this is heavily skewed towards groups I have interacted with or aren't too far from that. Additions are very welcome!

**Comment by hober** [comment]
https://lists.w3.org/Archives/Public/public-privacycg/2023Mar/0008.html

**Comment by hober** [comment]
https://lists.w3.org/Archives/Public/public-privacy/2023JanMar/0021.html

**Comment by npdoty** [comment]
Specific outreach to horizontal review groups, their experience and views may be insightful.
