### ISSUE TITLE
Privacy risks should be taken in context: Who is processing data and how?

### ISSUE THREAD

**Issue by dmarti** [w3ctag/privacy-principles#225]
**This is section 2 from the document "Commentary on the draft W3C Privacy Principles" from Movement for An Open Web, attached.**

Privacy risks should not be assumed out of context. They should be assessed in relation to exactly the data being
processed and whether the organization processing this data is linking it to people’s identity.

MOW agrees with the document’s proposition that expectations and risks to “privacy” must be judged by the factors
that “ultimately depend on the nature, scope context and purposes of the processing and how it is implemented.”

People have different expectations of privacy at work, at a café, or at home for instance. Understanding and
evaluating a privacy situation is best done by clearly identifying:

• Its actors, which include the subject of the information as well as the sender and the recipient of the
information flow (note that recipients might not always want to be recipients.);
• The specific type of data in the information flow; and
• The principles that are in use in this specific context.

MOW further agrees that in addition to the “specific context” the “specific type of data in the information flow” can
increase or reduce privacy risks to individuals. Processing of sensitive and special category data should be prohibited,
unless there is an established legal basis and “suitable measures to safeguard the data subject's rights and freedoms
and legitimate interests are in place.”9 When data is sensitive or belongs to the enumerated special categories,
privacy regulators recommend using heightened security relative to innocuous data.10

However, personal information alone is not the only risk to individuals. The recipient must link this information to
an individual’s identity to cause a privacy harm. There are of course other online harms that do not depend on
knowing an individual’s identity, such as fraud, sale of illegal goods or an online virus. However, given this document
is focused on defining privacy principles, we must ensure we are addressing this problem and that any proposed
remedies are tailored to address it.

Data protection regulators advise on how best to address privacy risks to consumers:

> “To assess the level of risk, you must consider both the likelihood and the severity of any impact on
individuals. High risk could result from either a high probability of some harm, or a lower possibility of
serious harm.”11

Accordingly, when reducing the risk to privacy we must consider the likelihood of whether a recipient will cause
specified harm to an individual, such as re-identification. If the legitimate business recipient receives information
not linked to identity and has appropriate organizational and technical measures (such as pseudonymization” to
provide the “necessary safeguards” for responsible processing of the personal data), GDPR and other privacy
regulations clearly state that there must be a balance between the state of the art, the cost of implementation on
businesses that are balanced against the varying likelihood and severity of risk to individuals:

> “Taking into account the state of the art, the cost of implementation and the nature, scope, context and purposes of processing as well as the risks of varying likelihood and severity for rights and freedoms of natural persons posed by the processing, the controller shall, both at the time of the determination of the means for processing and at the time of the processing itself, implement appropriate technical and organisational measures, such as pseudonymisation, which are designed to implement data-protection principles, such as data minimisation, in an effective manner and to integrate the necessary safeguards into the processing in order to meet the requirements of this Regulation and protect the rights of data subjects.1

When organizations implement these important and necessary safeguards as well as declare in writing they will not
reidentify the personal information they receive, such as on their privacy policy, this reduces the risks to individuals’
privacy.
Fortunately, the authors agree with the above data protection principle as they write one method of ensuring an
organization’s responsible data processing is by:

> “Specifying in its privacy statement that these types of data are kept separate and implementing policies and procedures to ensure the data is stored separately. (legal and procedural/compliance measures)”1

[2022.05.31-MOW-response-to-the-W3C-Privacy-Principles-EB.pdf](https://github.com/w3ctag/privacy-principles/files/10915527/2022.05.31-MOW-response-to-the-W3C-Privacy-Principles-EB.pdf)

**Comment by dmarti** [comment]
related: https://github.com/w3ctag/privacy-principles/issues/159

**Comment by darobin** [comment]
I can perhaps add some text pointing to https://academic.oup.com/idpl/article/12/3/163/6612144?login=false to strengthen this?

**Comment by dmarti** [comment]
It looks like we can close this one.

 * Privacy harms are possible without linking to any individual identity. All of the facts about myself that I most want to keep private are also true of at least `k` other people.
 * A legally binding declaration is only reliable when the person relying on the declaration and the party making the declaration share a legal jurisdiction.  On a **World Wide** web, the privacy principles must be workable even when there is no jurisdiction in common and a declaration would not be legally enforceable.
 
We should keep in mind that a privacy harm can happen when a person is classified as belonging to a group, even if which member of the group they are is not revealed, and that Web user agents and other software need to support the ability of people to safely visit sites outside their own country or region.
