### ISSUE TITLE
Don't imply the GPC has specific effects under the GPDR.

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#232]
@michaelkleber points out that https://w3ctag.github.io/privacy-principles/#opt-in-out has 

> A good example of a [global opt-out](https://w3ctag.github.io/privacy-principles/#dfn-global-opt-out) mechanism is the Global Privacy Control [[GPC](https://w3ctag.github.io/privacy-principles/#bib-gpc)].

followed shortly thereafter by

> under the [[GDPR](https://w3ctag.github.io/privacy-principles/#bib-gdpr)], the [person](https://w3ctag.github.io/privacy-principles/#dfn-individual) may be conveying objections to [processing](https://w3ctag.github.io/privacy-principles/#dfn-process) based on legitimate interest or the withdrawal of [consent](https://w3ctag.github.io/privacy-principles/#dfn-opt-in) to specific [purposes](https://w3ctag.github.io/privacy-principles/#dfn-purpose).

which implies that the GPC has that effect. Since the GPC has never been tested under the GDPR and was designed to match the CCPA, we shouldn't make that legal implication.

**Comment by jyasskin** [comment]
@dmarti will replace the GDPR reference with something about how respectful sites will take the GPC header as an indication of the user's preferences in order to reduce the amount they need to prompt the user, even though no law would require them to do that.

**Comment by darobin** [comment]
The way this is cited here makes it seem more prominent than it is in the text, where it's a parenthetical prefixed with "for instance", etc. But I agree that we can strengthen this by making a generic statement about how it could be understood, not mentioning the GDPR. For instance, [Bermuda's Privacy Commissioner has made this kind of suggestion about PIPA](https://www.privacy.bm/post/global-privacy-control-interoperability-in-action).
