### ISSUE TITLE
Clarify uses of "self-governing"

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#233]
In a comment, @michaelkleber understood "self-governing" to refer to approaches where an industry determines the rules for its own behavior, and I think that matches broad usage in industry. In https://w3ctag.github.io/privacy-principles/#privacy-labour, I think we instead mean approaches where users are expected to do their own work to govern how data about them leaks out into the world and is used.

We should be clear about what meaning we intend, and I suspect the best way to do that is to spell it out instead of using "self-governing" at all.

**Comment by darobin** [comment]
What you describe isn't self-governing, it's self-regulating. But I agree that this should be defined, we use it in multiple places. I'll take a stab at it.

**Comment by torgo** [comment]
As discussed on today's call I will make a PR seeing what it's like to remove/reword which we can then review.
