### ISSUE TITLE
Need a better source for "fiduciary" term

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#240]
https://w3ctag.github.io/privacy-principles/#user-agents says

> In academic research, this relationship with a [trustworthy agent](https://w3ctag.github.io/privacy-principles/#dfn-trustworthy-agent) is often described as "fiduciary" [[Fiduciary-UA](https://w3ctag.github.io/privacy-principles/#bib-fiduciary-ua)].

But [Fiduciary-UA] is a non-peer-reviewed paper that @darobin wrote. If we're going to make a claim about common academic practice, we should cite an academic source.

**Comment by darobin** [comment]
Let me put together a few good refs that cover the area, I just need to pick which ones might be best for the intended audience.

**Comment by wseltzer** [comment]
Balkin's Information Fiduciary? https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3700087
