### ISSUE TITLE
Abstract text

### ISSUE THREAD

**Issue by sandandsnow** [w3ctag/privacy-principles#25]
(For discussion) I would like to propose an alternate approach for the abstract text. Perhaps something along these lines:  

- There is general consensus globally that privacy is an important right or expectation that should be fulfilled, however, there is no universal definition of privacy. Instead, privacy frameworks have tended to scope privacy through a definition of “personal data” (or “personal information”) and a set of commonly agreed high-level privacy principles, such as those that are found in the [OECD Privacy Guidelines](https://www.oecd.org/sti/ieconomy/oecd_privacy_framework.pdf). However, in practice, there is a lot of variation in users’ privacy experiences. In part, this occurs because many privacy and data protection laws allow data collectors to rely on user consent to permit data practices or avoid implementing certain privacy protections.

- When users engage with the Web, they are generally aware when personal information is directly collected by a website, such as through the completion of an online form for a travel reservation. However, other forms of data collection via the Web are generally more opaque to users, such as fingerprinting and tracking (e.g., cross-site, cross-device, mouse and behavioural biometrics), and their privacy implications.

- The purpose of this document is not define privacy, but rather, to affirm the W3C’s commitment to a privacy-respecting Web, explain what protecting privacy means in the context of Web standards development and to articulate the W3C’s privacy principles for the Web.

**Comment by darobin** [comment]
I'm not convinced that this can work. Starting from the bottom, it's not clear to me how we can articulate privacy principles without, in some sense, defining privacy. If we're going to build Web things that support privacy and, where technology cannot suffice, encourage policy and governance methods that support privacy, don't we need to at least have a rough and ready sense of what privacy is?

**Comment by torgo** [comment]
We haven't closed this as there is useful stuff in here for the introduction.

**Comment by darobin** [comment]
I think that the [new introduction](https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/102.html#intro) addresses at least some of this. It's scoping the work to the Web and being open to there being rules/principles other than those defined in this document. WDYT?

**Comment by darobin** [comment]
Closing as this seems to have been overtaken — please reopen if needed.
