### ISSUE TITLE
refined example about privacy of small groups

### ISSUE THREAD

**Issue by npdoty** [w3ctag/privacy-principles#251]
In addressing collective privacy, it would be useful to have a cogent example about the privacy of groups, in particular of small groups. Both, there may be an important privacy interest about what can be learned about a small group (the students in the class, say) even if no individual's data is learned, and there may be an important privacy interest in being able to target a small group based on certain properties, even if the targeting is done without data collection on those individuals.

**Comment by dmarti** [comment]
One good example might be jury pools, which are pretty easy to identify with conventional adtech/martech (`k` people who did some trackable activity somehow related to the immediate area of the courthouse on the 1st day of jury selection for a major trial, and have not been seen in the area in the previous 90 days). Last time I had to do jury duty, most of the people in the jury room were on their phone most of the time they were not in the actual courtroom.
