### ISSUE TITLE
Mention limitations on data rights

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#252]
@jbradleychen pointed out that our [Data Rights](https://w3ctag.github.io/privacy-principles/#data-rights) section is very absolute, while the sources we cite for these rights have limitations. For example, we just say

> The right to erase data about oneself.

But https://gdpr-info.eu/art-17-gdpr/ says

> [The right to erasure] shall not apply to the extent that processing is necessary: for exercising the right of freedom of expression and information; for compliance with a legal obligation which requires processing by Union or Member State law to which the controller is subject or for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller; for reasons of public interest in the area of public health in accordance with points (h) and (i) of [Article 9](https://gdpr-info.eu/art-9-gdpr/)(2) as well as [Article 9](https://gdpr-info.eu/art-9-gdpr/)(3); for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes in accordance with [Article 89](https://gdpr-info.eu/art-89-gdpr/)(1) in so far as the right referred to in paragraph 1 is likely to render impossible or seriously impair the achievement of the objectives of that processing; or for the establishment, exercise or defence of legal claims.

Brad is particularly concerned about cases where someone who's abused a system wants to have the evidence of their abuse erased so that they can go on to abuse more people, or wants to opt out of automated detection of abuse, or wants to access the data that the system used to identify their abuse so that they can more easily evade the system next time.

What can we say about cases where people give up some of their rights?

**Comment by torgo** [comment]
We agreed on today's call that "we think this worry is covered by the other limitations on the whole document" and therefore we're closing this.
