### ISSUE TITLE
Suggestions on Introduction

### ISSUE THREAD

**Issue by chrisn** [w3ctag/privacy-principles#253]
Hi TAG, I've been reading through the document and have a few suggestions. This is just on the initial part of the document, I may file more issues as I continue reading.

### How This Document Fits In

"a law in one country does not (and should not) change the whole Web's architecture" - this is phrased strangely, I suggest something like "significantly change the architecture of the Web"

### Audiences for this Document

"designers should consult" - designers aren't mentioned in the list of primary audiences, should this be "authors of web specifications"?

### An Introduction to Privacy on the Web

The structure of this section could be improved to aid readability. 

"Asymetries of power" is an important concept but the description is interrupted by the paragraphs starting "The Web is a social and technical system" and "Few architectural principles are absolute". I recommend consolidating the description of asymmetries of power (essentially, combine paragraph 5 and paragraph 2 in this section).

The paragraph beginning "Few architectural principles are absolute" could be better placed in "How This Document Fits In", as could the part about "Our goal is not to cover all possible privacy issues".

Not sure if this explains clearly,  so I could create a PR to illustrate if that's helpful.

**Comment by torgo** [comment]
Hi @chrisn for point 3 above ("An Introduction to Privacy on the Web") yes can you please write a PR for us on that?

**Comment by jyasskin** [comment]
And I'll volunteer for the Audiences PR.

We think the "How This Document Fits In" point isn't enough of a difference to spend much time on. The existing text about the "whole" Web is useful to contrast with a single government, and maybe this should link to https://www.w3.org/TR/ethical-web-principles/#oneweb, but we didn't really want to spend a lot of time wordsmithing this sentence.
