### ISSUE TITLE
People's Agents

### ISSUE THREAD

**Issue by chrisn** [w3ctag/privacy-principles#255]
This section discusses user agents, so I'm wondering what distinction you are making between a user agent and a people's agent. If a People's Agent is something other than a UA, I recommend giving it a definition.

A minor editorial suggestion for this section: Split the second sentence under "Duty of Protection": "It is insufficient to just encrypt at rest and in transit. The user agent must also ..."

"Many of the principles described in the rest of this document" - Here, "principles" links the the earlier definition in section 1. But it seems there are two sets of principles being described: a general set (Section 1), and a set that this document is laying out for the web (Section 2). So the link seems inappropriate here, as this sentence is introducing the web-specific principles defined in the rest of the document.

**Comment by jyasskin** [comment]
For the first paragraph, I'll send a PR to s/People's Agents/User Agents/. We were trying to use "person" instead of "user" in general, but I think we overdid it there.

**Comment by jyasskin** [comment]
And #264 fixes the third problem.
