### ISSUE TITLE
Feedback on section 1.4 "Incorporating Different Privacy Principles"

### ISSUE THREAD

**Issue by chrisn** [w3ctag/privacy-principles#256]
The title of this section doesn't really capture what this section describes, which is how to balance or resolve tensions between different principles. I don't have a good suggestion, but "Incorporating" doesn't really capture it .. maybe "Resolving Tensions Between" ?

The W3C TAG Ethical Web Principles should be cited in reference style rather than linked inline (and similar for Target Privacy Threat Model, later in the document).

"if it believes that person has broken the rules" - It's not clear which rules this refers to. Is it the same thing that's described later as "violates the norms of a service they're using"? If so I recommend aligning the language.

An observation on Example 5: This is related to current work in progress ("are trying to...", and discussion of conversion attribution APIs), and so will eventually become dated as things progress. That may be fine if you plan to revisit the guidance in the document in the future, but it could be worth either rephrasing to be less specific to the here and now or moving elsewhere (e.g., input to PATCG).

**Comment by torgo** [comment]
We agreed today not to... change the name of the section as there were strong feelings on both sides... However we're going to take up the 2nd part of this suggestion. Jeffrey will do a PR.

**Comment by chrisn** [comment]
Sounds good to me, thank you.

**Comment by jyasskin** [comment]
I think the TAG does plan to maintain this document as we see how Example 5 turns out, so I didn't tweak the language there.
