### ISSUE TITLE
Add link to "site" definition under "Cross-site recognition"

### ISSUE THREAD

**Issue by chrisn** [w3ctag/privacy-principles#257]
In section 2.1.1, I suggest that "site" in "Cross-site recognition is when a site determines" should link to its definition.

(I notice that "site" appears in lots of places without being linked, but I think worth adding a link here even if not needed everywhere.)

As an aside, I'm assuming you prefer people to raise issues rather than PRs, but please let me know as I'm happy to make PRs for smaller suggestions such as this.

**Comment by jyasskin** [comment]
Thanks! We love PRs when you're comfortable making them.
