### ISSUE TITLE
Definitions 2.1 to 2.4 (part)

### ISSUE THREAD

**Issue by sandandsnow** [w3ctag/privacy-principles#26]
**Person:** A suggestion to replace "person" with "individual" because, at least in some jurisdictions, the term "person" or "persons" could include corporations or bodies politic
**Personal Data:** Definitions of "personal data" or "personal information" are generally not limited to "identifiers". While the use of identifiers, especially persistent and globally-unique, are of particular privacy concern in Web standards, I do not think the definition should be this narrowly scoped. Separately, consider adding the scenario where a user can be singled out, even if not identified as X.
**Pseudonymous:** Review this definition. For instance, I could imagine a scenario where the identifiers used in the data  under the direct and exclusive control of the first party are not in fact pseudonymous (e.g., an email address that contains the user's name). Is the purpose to define what pseudonymous identifiers are, rather than pseudonymous data?
**Vulnerable person:** Is there a reason why the definition is focused on whether an individual is capable of giving meaningful consent (or perhaps I misread the definition)? Perhaps there are other ways that individuals are vulnerable in terms of privacy (e.g., power-imbalance, personal attributes which might cause them to be easily singled-out or identified as a person with x characteristics, etc.)
**Party:** For clarification, why does the definition of a "party" include a set of legal entities? Is this because of the first party, third party distinction typically used in W3C documents? (They might be related parties, but they are separate legal entities, which may have different privacy obligations or entitlements to use "personal data". )
**First Party:** It's helpful to provide some examples of where the user does not intend to interact with the first party. Would it also be helpful to add some examples of where it is generally agreed that the user does intend to interact?
**Service Provider or Data Processor:** For clarification, why does the data processor processing data on behalf of the first party need to be treated as the first party? (also relevant to the definition of **shares**.
**Purpose:** If we are prescribing characteristics to "purpose" such as "specific", there are other characteristics that should be added such as "reasonable, necessary, fair".

**Comment by torgo** [comment]
Reviewed and discussed in [today's call]().

**Comment by darobin** [comment]
For **pseudonymous**: make it clearer that embedded data (as per @sandandsnow's example of a name in an email address) that could lead to reidentification should be covered by "technical means" and also make it clearer that we don't need there to be a third party.

**Comment by darobin** [comment]
About **party**: make it stricter, and remove _set_ of legal entities.

**Vulnerable**: make it a lot less about consent and more about autonomy and asymmetries of power.

**Comment by darobin** [comment]
Also for vulnerable people: Christine notes that vulnerable people, in addition to asymmetry of power, may also be at greater risk of harm.

**Comment by wseltzer** [comment]
Missed the prior discussion of pseudonymous, but also https://github.com/w3ctag/privacy-principles/issues/33

**Comment by darobin** [comment]
[more notes from meeting]
@sandandsnow correctly points out that we need to be clear that 1P/3P are being defined because they are terms of art but there is not endorsement of the idea that 1P === good.

**Comment by darobin** [comment]
Other good idea from @sandandsnow: don't try to fold service providers into first party but instead come up with a typology that provides useful distinctions such as in the perimeter for a given legal entity, separately subpoenable, accountability and could render a richer account of the different properties of different data flow arrangements.

For purpose: we keep specific, but it would be also good to capture that, normatively, we'd like them to also be reasonable, fair, etc.

**Comment by darobin** [comment]
Go through this and make sure it's all incorporated.

**Comment by sandandsnow** [comment]
Closing this issue as the comments have been addressed in re-writes.
