### ISSUE TITLE
What are "k-anonymity attacks"?

### ISSUE THREAD

**Issue by martinthomson** [w3ctag/privacy-principles#284]
I'm assuming that this refers to the idea that k-anonymous datasets can in many cases be re-identified; see [[cohen](https://arxiv.org/abs/2202.13470)] or the fact that re-identification of "anonymized" datasets is now a game for some.

It would help if this were clearer.  The term is used as if it were obvious, but it very much isn't.

**Comment by torgo** [comment]
Closed on the basis of #337
