### ISSUE TITLE
"Pseudonymous" with respect to whom?

### ISSUE THREAD

**Issue by wseltzer** [w3ctag/privacy-principles#33]
The document defines "pseudonymous" with respect to a first party controlling the linkage of identifiers and unlinking them from third parties. Many users would expect a definition in which they (the "second party"?) were in control of their pseudonymity. 

Maybe we need a modifier in the defined term, as in "pseudonymized by a first party"?

**Comment by torgo** [comment]
Discussion got to distinguishing Pseudonymous in general vs Pseudonymous with respect to... a rewrite is ongoing.

**Comment by jyasskin** [comment]
Was this fixed by #30? "Pseudonymous" got replaced by:

> We talk of [controlled de-identified data](https://w3ctag.github.io/privacy-principles/#dfn-controlled-de-identified-data) when there are strict controls that prevent the re-identification of people described by the data except for a well-defined set of purposes.
