### ISSUE TITLE
Re: 3.1 Unwanted same-site recognition

### ISSUE THREAD

**Issue by sandandsnow** [w3ctag/privacy-principles#34]
* Propose amending the sentence “Users of most instantiations of the web platform expect that if they visit a site on one day, and then visit again the next day, the site will be able to recognize that they're the same user” to add words along the lines of “but they generally do not expect that the site will track their interaction with the site over time (such as everything they have viewed, for how long, etc.)”. Propose replacing “this” in the following sentence to “Same-site recognition allows …”.
* Would it make sense to have a separate section entitled “Unwanted same-site tracking”?
* Editorial: Remove “only” from “A privacy harm only occurs …”
* In which category would we describe the privacy harm from a single instance of site-recognition? (e.g., where a site is inappropriately detecting data to infer whether a user has a visual or other impairment).
* Consider adding synonymous terms to “private browsing” such as incognito mode. Also, add effectively synonymous terms for “profiles” such as containers or container tabs.
* Editorial: Add “or more” after “expert their two visits ...”
* Add to the list where a user might expect their two visits will not be associated:
	* Use extensions or add-ons to block tracking
	* Where they believe privacy or data protection laws would not permit tracking
* Even though this is discussed in the opening text of the section, considering adding a sentence “A user might expect that their two visits would be associated for specific purposes such as to maintain the contents of their shopping cart or to avoid having to log in again”.
* For discussion: What recommendations (namely, MUST or SHOULD statements) should we include for this section? A starting point regarding fingerprinting appears in the PING Group Note on [Mitigating Browser Fingerprinting in Web Specifications]( https://www.w3.org/TR/fingerprinting-guidance/).

**Comment by darobin** [comment]
@sandandsnow to double check that this is in and close if so.

**Comment by sandandsnow** [comment]
Re: 2.1.1.1. Same-site recognition, suggest amending these parts of the text as follows:
" ... While [User agents](https://w3ctag.github.io/privacy-principles/#dfn-user-agent), in general, are not able to determine exactly where intra-site [context](https://w3ctag.github.io/privacy-principles/#dfn-context) boundaries are, or how a site allows a [person](https://w3ctag.github.io/privacy-principles/#dfn-individual) to express that they intend to change [identities](https://w3ctag.github.io/privacy-principles/#dfn-identity) and/or they do not wish site to recognise them on subsequent visits, they are not able to enforce that sites actually separate [identities](https://w3ctag.github.io/privacy-principles/#dfn-identity) at those boundaries. 

Principle: Sites should allow a [person](https://w3ctag.github.io/privacy-principles/#dfn-individual) to use separate [identities](https://w3ctag.github.io/privacy-principles/#dfn-identity) for new visits to the site unless the person explicitly expresses the same [identity](https://w3ctag.github.io/privacy-principles/#dfn-identity) for the subsequent visits. [User agents](https://w3ctag.github.io/privacy-principles/#dfn-user-agent) should ensure that, when a [person](https://w3ctag.github.io/privacy-principles/#dfn-individual) visits a site from different [partitions](https://w3ctag.github.io/privacy-principles/#dfn-partition), that the site cannot quickly determine that the visits probably came from the same person, unless the person explicitly expresses the same [identity](https://w3ctag.github.io/privacy-principles/#dfn-identity) for the visits, or preventing this correlation would break a technical feature that is fundamental to the Web.

...

The attributes can be exposed as information about the [person](https://w3ctag.github.io/privacy-principles/#dfn-individual)'s device including [2.3 Sensitive Information](https://w3ctag.github.io/privacy-principles/#hl-sensitive-information). For example:

...

- What accessibility devices are connected ...

**Comment by sandandsnow** [comment]
Re: "This principle is limited in cases that only affect a small fraction of people who use the web because people may configure their systems in unique ways, for example by using a browser with a very small number of users. As long as a tracker can't track a significant number of people, it's likely to be unviable to maintain the tracker. However, this doesn't excuse making small groups of people trackable when those people didn't choose to be in the group."

I would prefer this we not limit this principle, especially not based on the number of users. Suggest deleting this text.

**Comment by sandandsnow** [comment]
Thanks. It seems my comments above have been overtaken by the re-write. Thanks. No further action on this from me.
