### ISSUE TITLE
Re: Opt-in, Consent, Opt-out, Global Controls

### ISSUE THREAD

**Issue by sandandsnow** [w3ctag/privacy-principles#35]
* First sentence: Change “control” to “express a preference for what processing is done to their data”. 
* Second sentence: “uses” would seem more relevant in this context than “purposes”, or perhaps “uses and/or purposes”.
* Informative website regarding dark patterns: https://darkpatternstipline.org/harms
* For discussion: the default privacy tiers. For example, it does not seem appropriate to require people who are vulnerable to opt-out. Consider also adding text about the privacy implications of choosing to opt-out, especially when the majority of users does not.
* Consider adding text about people rarely changing the default and the consequences that has for their privacy.
* Permissions are relevant to consent. Take a look at Nick Doty’s post here: https://www.w3.org/blog/2019/07/adding-another-permission/. It could be a helpful starting point for recommendations. Would it make sense to add another section under 3 that covers permissions?

**Comment by jyasskin** [comment]
In https://github.com/w3ctag/privacy-principles/pull/94#issuecomment-1010535916, @sandandsnow also mentions

> We might want to include a statement to the effect that some controls are in practice illusory because the person or user effectively has no choice, accept the terms or don’t use the service.
