### ISSUE TITLE
"should best" and collective privacy

### ISSUE THREAD

**Issue by martinthomson** [w3ctag/privacy-principles#351]
> [Principle](https://w3ctag.github.io/privacy-principles/#principle-collective-privacy): Groups and various forms of institutions should best protect and support autonomy by making decisions collectively rather than individually to either prevent or enable data sharing, and to set defaults for data processing rules.

I'm a little unclear on the grammatical intent of the phrasing of this statement, particularly around the "should best" part.

However, I think that this is making too strong a statement.  There are cases where collective action on privacy, or collective setting of rules, has a great deal of power and utility.  @jyasskin gave a great example in the TPAC session here that highlights how standards development is a good way to use collective decision-making processes to achieve positive privacy outcomes, particularly for cases where the issues are complex.

However, the way that this is phrased could be read to imply that collective setting of rules is strictly superior to engagement with individuals.  I'm guessing that that is unintentional, so I suggest that some editorial work is needed to clarify the intent if that is the case.  Otherwise, I think we might want to debate the point.

**Comment by jyasskin** [comment]
Reopening until Martin confirms that this issue is closed. #363 had some discussion that suggested a larger issue.
