### ISSUE TITLE
Concrete examples re: features for responsive design

### ISSUE THREAD

**Issue by eeeps** [w3ctag/privacy-principles#352]
Perhaps this is something that would belong in some kind of companion document as discussed in the recent TPAC breakout, but I would love some kind of concrete example, somewhere, about how to apply the documents' principles when designing specific features for responsive design. Responsive design features are often in fundamental tension with data minimization.

For instance, I have found reading through https://fingerprint.com/blog/disabling-javascript-wont-stop-fingerprinting/ concrete and useful, when thinking through questions like:

- How problematic is revealing a user's viewport-width via media queries? (somewhat but not very, because because it's not stable for a significant portion of users [desktop])
- How granular should new media queries around HDR or wide gamut colors be? (as coarse as possible, because these values are very stable for everyone)
- How effective have User-Agent mitigations over the yeas been? (very!?)

Examples of shipping features that would receive negative privacy reviews if they were proposed today would be especially helpful when building a mental model of how to think through tradeoffs.

**Comment by npdoty** [comment]
This might be a useful issue specific to fingerprinting mitigation guidance, over here: https://github.com/w3c/fingerprinting-guidance/issues

That document needs updates, and could try to include more examples along these lines.
