### ISSUE TITLE
Separate device owner and user agent owner

### ISSUE THREAD

**Issue by reillyeon** [w3ctag/privacy-principles#353]
A device owner may configure operating system-level features such as VPNs which affect user agent behavior by changing the behavior across all applications, including the user agent. The privacy principles could differentiate between a "device owner" who has broader control over the platform and a "user agent owner" who may only control a single browser profile associated with a managed account.

CC @jyasskin.

**Comment by npdoty** [comment]
Might be useful to refer to those who administer or configure software on a device, which is a pretty common and generic category, but not an "owner" of a profile of user software.
