### ISSUE TITLE
Breadth of consultation

### ISSUE THREAD

**Issue by M4AOW** [w3ctag/privacy-principles#357]
How was input was sought from advertising and publishing companies or their trade bodies to the Privacy Principles? – see LumaScapes for a visual representation of the market. [1]

[1] https://lumapartners.com/lumascapes/.

Tim Cowen - legal counsel for Movement for an Open Web.

**Comment by darobin** [comment]
We consulted a wide cross-section of industry, this was discussed with the IWA which has very strong representation from the adtech industry, it was brought directly for discussion to publisher groups (e.g. EPC, NMA, DCN), and the W3C Advisory Committee has further representatives from these. We have received comments, which we've incorporated, and words of support.

I further note that wide review is still open and you should feel free to reach out to whoever you think should speak up.
