### ISSUE TITLE
Movement for an Open Web (MOW) review

### ISSUE THREAD

**Issue by M4AOW** [w3ctag/privacy-principles#358]
Before MOW commences a subsequent review I’d like to know if the current draft considers the feedback provided by Movement for an Open Web in June 2022? [1]

 

[1] https://movementforanopenweb.com/wp-content/uploads/2022/06/2022.05.31-MOW-response-to-the-W3C-Privacy-Principles-EB.pdf

Tim Cowen - legal counsel for Movement for an Open Web.

**Comment by darobin** [comment]
It does, and changes were made accordingly, as you can find out for yourself in this very issue tracker.
