### ISSUE TITLE
Motivation and/or threat model for data minimization

### ISSUE THREAD

**Issue by yoavweiss** [w3ctag/privacy-principles#370]
One question that came up when discussing data minimization and potential mitigations for exposing ancillary data is: "why should we minimize data exposure?"

Knowing what the threat we're protecting against is generally useful when thinking through mitigations for that threat.

I think it'd be useful to clearly state *why* we need to minimize data exposure, as well as explaining that different types of data may have different threat models:
* Some types of data are sensitive on their own and expose something particular about the user (e.g. accessibility preferences)
* Other types of data are not sensitive, but can contribute to the overall fingerprint (e.g. system load)

That can help WG that think through ancillary data exposure and potential mitigations.

**Comment by dmarti** [comment]
We cover the issue of sensitive information in [2.4](https://w3ctag.github.io/privacy-principles/#hl-sensitive-information).

> System designers should not assume that particular information is or is not sensitive. Whether information is considered sensitive can vary depending on a [person](https://w3ctag.github.io/privacy-principles/#dfn-individual)'s circumstances and the [context](https://w3ctag.github.io/privacy-principles/#dfn-context) of an interaction, and it can change over time.

It's not really possible to tag the data itself as sensitive/non-sensitive. It depends on context ("occupation" might be non-sensitive for a bank manager on a job listing site, but sensitive on a fanfic site) and the ability of parties to make sensitive inferences from apparently non-sensitive data points.

**Comment by yoavweiss** [comment]
I'm not suggesting we should explicitly tag data, but we should have some threat models that we're trying to defend against. Otherwise, we will not be able to make any reasonable trade-offs or make the wrong ones.

**Comment by npdoty** [comment]
+1 to jyasskin on the reasoning for minimization, and I believe that's the consensus of the task force (13 December 2023). 

Just to clarify, there are still important potential differences in the sensitivity, we just note that those things are not inherent in particular data types, and often vary by person or context. That's part of the justification for general data minimization.
