### ISSUE TITLE
Be consistent/intentional on "must" vs "should" and RFC 2119 language

### ISSUE THREAD

**Issue by npdoty** [w3ctag/privacy-principles#371]
Are we intending to use RFC 2119 normative language when we say "must" or "should" in these principles?

If so, we should cite 2119.

In general, it seems like principles are typically "should" language -- they are high-level and involve implementation with many other considerations. But we may want to review which ones say "must" and whether those are absolute.

**Comment by darobin** [comment]
Add a conformance section that says something like "we are not using strict RFC 2119 language because there is no evident conformance class but we do distinguish between should and must in principles"
