### ISSUE TITLE
Tweak "disabling privacy APIs with new information" 

### ISSUE THREAD

**Issue by torgo** [w3ctag/privacy-principles#372]
Just making a note here that on today's call I agreed to try to make a suggested change to We could tweak https://w3ctag.github.io/privacy-principles/#principle-disabling-ancillary-apis-with-new-information to remove the implication that the default should be enabled.

**Comment by yoavweiss** [comment]
https://github.com/w3ctag/privacy-principles/issues/377 and https://github.com/w3ctag/privacy-principles/issues/376 seem relevant here.
