### ISSUE TITLE
Consider removing the definition of "vulnerable people".

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#373]
@pes10k points out that we don't use it much, and that we might be able to remove the definition.

@rhiaro points out that it's useful to remind readers that different people are vulnerable in different situations.

If we keep it, https://w3ctag.github.io/privacy-principles/#vulnerability should link to it.

**Comment by pes10k** [comment]
just to follow up on conversation from the call

my PoV is that if we're defining "vulnerable people" to include "all employees with a boss," then thats so broad a definition (and includes such a large % of people) that it obscures @rhiaro 's point (which i share), that spec authors should keep in mind certain populations of people that have exceptional privacy needs and considerations.

**Comment by npdoty** [comment]
I think it's useful to have a definition, and for that definition to reflect that vulnerability depends on context, including scenarios like employment and parenthood/guardianship.

**Comment by npdoty** [comment]
Or could the editors make the current quoted word into a sentence with a proper linked definition?

**Comment by dmarti** [comment]
I will add a PR for this based on meeting notes

https://github.com/w3ctag/privacy-principles/blob/main/meetings/2024-01-17-minutes.md

**Comment by jyasskin** [comment]
Fixed by #402.
