### ISSUE TITLE
Revisit 2.4 Sensitive Information section

### ISSUE THREAD

**Issue by pes10k** [w3ctag/privacy-principles#388]
There are some aspects of this section that might benefit from a revision (there are differing opinions).

- whether we should list hints at whether certain types of data are sensitive, while also saying that the reader should not assume certain data is sensitive or not
- whether the section is needed at all (since nothing in the document hangs off whether data is sensitive or not)

**Comment by darobin** [comment]
@darobin Cut last part after "When considering" and use text from minutes.

**Comment by darobin** [comment]
Closed by #420
