### ISSUE TITLE
Opt-in vs. Opt-out

### ISSUE THREAD

**Issue by torgo** [w3ctag/privacy-principles#405]
Channeled from  https://social.mkj.earth/@mkj/111976552125719593:

> It seems to me to focus too much on active opt-out rather than active opt-in.
>
> Example:
>
> If I visit example.com and get a pop-up asking me for my cookie preferences before being able to proceed, even if there is a clear option to *opt-out* reject all cookies, that requires me to take affirmitive action before being able to proceed.
>
> If instead there is a top or bottom bar saying "to enable additional features, set cookie preferences", that allows *opt-in* to gain additional value.

**Comment by darobin** [comment]
This seems to be just relitigating consent? I don't see in the draft anything that's about "active opt-out".
