### ISSUE TITLE
Should we be discussing solutions?

### ISSUE THREAD

**Issue by jonathanKingston** [w3ctag/privacy-principles#42]
Should we be discussing potential solutions that user agents are able to take to mitigating the vectors in the document?

1. Quantization of data
2. Reduction of entropy
3. Reduced timing
4. Addition of noise
5. etc

**Comment by samuelweiler** [comment]
IMHO, only to the extent that it helps us clarify what we're otherwise saying.  

I'm happy with mitigations being in the [Self-Review Questionnaire](https://w3ctag.github.io/security-questionnaire/).

**Comment by sandandsnow** [comment]
I am in favour of considering practical solutions in this exercise as they will test/inform our drafting of principles and we might discover gaps in what should be included in the questionnaire (or elsewhere).

**Comment by darobin** [comment]
Yes.
