### ISSUE TITLE
Non-retaliation as a design principle

### ISSUE THREAD

**Issue by martinthomson** [w3ctag/privacy-principles#425]
https://github.com/w3ctag/design-principles/pull/476/files has a principle that we've found to be useful in other contexts.  This document talks about a requirement to not retaliate, but it doesn't talk about how systems might be structured to avoid the possibility of retaliation.

**Comment by martinthomson** [comment]
https://w3ctag.github.io/privacy-principles/#non-retaliation or https://w3ctag.github.io/privacy-principles/#support-choosing-info might include some added language on this.

**Comment by rhiaro** [comment]
Related to #418

**Comment by hober** [comment]
Closing as a duplicate of #418.
