### ISSUE TITLE
Seeking horizontal review?

### ISSUE THREAD

**Issue by aphillips** [w3ctag/privacy-principles#452]
I saw the announcement of the call for wide review of Privacy Principles today, but I do not have or at least am not aware of a request for an I18N Review. While NOTE status documents are not obliged to seek such review in the Process, I feel that strongly opinionated documents on the Statement track probably should consider horizontal concerns. There may be nothing here to really say, but then, I have not read the entire document yet.

I note that there has recently been a tension between I18N (in which information about user preferences can benefit the language and cultural relevancy of a service or site) and Privacy (in which gathering that information can lead to negative consequences such as fingerprinting).

**Comment by torgo** [comment]
Hi - there was an i18n review https://github.com/w3c/i18n-request/issues/227 which was closed.

**Comment by aphillips** [comment]
You're correct. I missed it in my search.

Thanks.
