### ISSUE TITLE
Precise the definition of personal data

### ISSUE THREAD

**Issue by lknik** [w3ctag/privacy-principles#48]
While I see that "personal data" are being precisely defined by a subtick.

Perhaps it would be possible to adapt "We define personal data as any information relating to a person such that" to "_We define personal data as any information relating to **identified or identifiable person** such that_".

This is motivated with the previous 40 years in data protection, where defining "_personal data" as """personal data" means any information relating to an identified or identifiable individual"_" on a standard basis. Specifically the above definition withstood the test of time, having been included in 1980 in [OECD Guidelines](https://www.oecd.org/sti/ieconomy/oecdguidelinesontheprotectionofprivacyandtransborderflowsofpersonaldata.htm) and in 1981 in [Convention 108](https://rm.coe.int/1680078b37), and in fact in  2016 in the [GDPR](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=EN). This proves that the definition is standard and static.

**Comment by darobin** [comment]
The latest version of #30 should fix this.
