### ISSUE TITLE
3.1 Unwanted same-site recognition and cookie matching

### ISSUE THREAD

**Issue by lknik** [w3ctag/privacy-principles#49]
Hello,

Considering _3.1 Unwanted same-site recognition_ 

I feel it limits itself to standard and well known technical privacy risks. It maintains that _cross-site recognition_ may be generally be made only using:
_This recognition is generally accomplished by either "supercookies" or browser fingerprinting._. 

However, we do know that there may be other ways of doing these things.

What about other tools for cross-site recognition, such as cookie matching ([1](https://developers.google.com/authorized-buyers/rtb/cookie-guide), [2](https://www.ndss-symposium.org/wp-content/uploads/2017/09/05_5_0.pdf)), or other similar schemes (e.g. redirection-based) of the kind? (it also works cross-site)

**Comment by darobin** [comment]
I address this in #201.
