### ISSUE TITLE
3.3 Sensitive information disclosure - more examples

### ISSUE THREAD

**Issue by lknik** [w3ctag/privacy-principles#50]
What does "..." mean in this point? That it is subject to expansions or that the list is not exhaustive?

In any case may we also add:
- user's health situation
- user's behavioral aspects
- user's racial profile

**Comment by jyasskin** [comment]
The "..." here was a "TODO: think of more examples", so thanks for thinking of more examples. When we redraft this section, we should probably be clearer that this list can never be exhaustive.

On these specific additions, what do you mean by "behavioral aspects"? Is it something like "habits", or "ways the user tends to behave", or something else?

**Comment by darobin** [comment]
Fixed in #163.
