### ISSUE TITLE
Go through list of suggestions from the WebAdv "success criteria" that some had proposed

### ISSUE THREAD

**Issue by darobin** [w3ctag/privacy-principles#61]
Sift through it for things that are relevant to privacy.

https://github.com/w3c/web-advertising/blob/main/success-criteria.md#interests-of-society (and following sections).

**Comment by dmarti** [comment]
The point on free elections might be usefully generalized to deceptive communications in general. The same data practices that enable targeted political content and advertising are also used for run-of-the-mill scams. (For example, offering a counterfeit product only to people who are unlikely to work for or with the makers of the original.)

https://blog.zgp.org/when-can-deceptive-sellers-outbid-honest-sellers-for-ad-impressions/

**Comment by darobin** [comment]
I've done the following:
* Punted self-censorship to a future issue (#104)
* Added a [new subsection](https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/102.html#transparency) about the need to enable transparency for research/accountability purposes. That includes mention of access rights as well as algorithmic explainability. I would prefer that this document _not_ have to go into the latter in any detail, if we can.
* Added a [section on data rights](https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/102.html#data-rights) that is meant to include erasure, access, rectification, and portability but I haven't filled it out yet.
