### ISSUE TITLE
Find a place to mention ways users signal they dont want unwanted profiling

### ISSUE THREAD

**Issue by pes10k** [w3ctag/privacy-principles#63]
* Use a browser that offers tracking protection
* Use extensions or add-ons to block tracking
*	Choose no, deny or disallow when offered a choice about tracking cookies (or tracking in general)
*	Use their browser's private or incognito browsing mode
*	Use a clean browser profile, container, partition or other mode to isolate web site visits
*	Explicitly clear the site's cookies or storage
* Use a VPN to hide their location

**Comment by pes10k** [comment]
Additional related text that might be good to re-integrate elsewhere in the document

```Some of those strategies could reveal attributes or characteristics that would lead
unexpected profiling, were a site able to learn them such as:

* Whether a person is using a VPN to hide their location
* Whether a person is using a clean browser profile, container, partition or
  other mode to isolate web site visits
* Demographic information, even in the presence of other privacy protections
  (e.g., k-anonymity, differential privacy)
```

**Comment by dmarti** [comment]
Some of these signals might be initiated by a system administrator, network owner, or middlebox device without the knowledge of the user.

  * content filters in routers
  * centrally managed browser settings
  
  See #2
