### ISSUE TITLE
Clarify what topics are covered in this document, vs other PING and TAG docs

### ISSUE THREAD

**Issue by pes10k** [w3ctag/privacy-principles#7]
Currently the [PING Charter](https://www.w3.org/2019/09/privacy-ig-charter.html) defines a [A Target Privacy Threat Model for the Web](https://w3cping.github.io/privacy-threat-model/) as PING deliverable.  There are also related TAG documents, such as the [Ethical Web Principles](https://www.w3.org/2001/tag/doc/ethical-web-principles/).

This group should define what topics and content are covered in the document this group will be working on, and whats better covered in other PING and TAG documents.

**Comment by pes10k** [comment]
As a first cut at this problem, I can write up a summary of existing and planned documents, and what topics should be covered in each

**Comment by hober** [comment]
It was my impression, during some of the discussion which lead to this TF being created, that the detailed documentation of specific threats and possible mitigations wouldn't end up in this document, but would instead continue in PING as the threat model document.

**Comment by torgo** [comment]
As discussed in call today, there should still be a privacy threat model doc in ping. We should further clarify what should be in this doc and what won't be. Should be a section in this doc "what this document is and what it is not" with links to other docs - e.g. the privacy & security questionnaire.

**Comment by darobin** [comment]
More specific issue in #91 .
