### ISSUE TITLE
Re: privacy principles by category

### ISSUE THREAD

**Issue by sandandsnow** [w3ctag/privacy-principles#70]
Taking another look at the draft content in this section as it reads now, it appears to discusses privacy issues and/or privacy threats (e.g. cross-site recognition) rather than privacy principles. Let me suggest we change the title and extract any text that goes to "principles" into a new section. Also, let me suggest we spend some time in our meeting tomorrow enumerating the principles, (e.g. distilling the general from the specific).

**Comment by darobin** [comment]
Overtaken by #89.
