### ISSUE TITLE
Consider adding a section on cross-device tracking

### ISSUE THREAD

**Issue by sandandsnow** [w3ctag/privacy-principles#71]
There are many ways that sites try to engage in cross-device tracking. Perhaps the most well-known in media, was/is ultrasonic tracking beacons, but this potential threat also came up in discussions on sensor APIs such as the ambient light sensor API.

**Comment by npdoty** [comment]
+1, tracking on a browser across modes or beyond attempts to clear state, across browsers on the same device, or across devices, are important and distinct examples of users not having control to separate contexts.

**Comment by torgo** [comment]
We can close based on #186.
