### ISSUE TITLE
How do safety systems relate to privacy

### ISSUE THREAD

**Issue by darobin** [w3ctag/privacy-principles#73]
We should consider things that use attack pathways for pro-user, defensive purposes, and how we should reason about it:

* Detecting tags/beacons in the surrounding space in order to report that a person may be tracked by someone else.
* Fraud prevention uses, for invalid traffic detection
* Relying on geolocation to check that a person's credit card purchases are valid

**Comment by jyasskin** [comment]
@jbradleychen suggested that we distinguish a party's safety-oriented systems from its revenue-oriented systems, and add a principle that data use oriented toward safety and anti-abuse is presumptively appropriate, while data use oriented toward increasing revenue has many more restrictions. That's not to say that _all_ anti-abuse data use is appropriate, just that it's more likely to be.

**Comment by dmarti** [comment]
From the browser point of view it seems like there would be two kinds of anti-abuse: anti abuse of the user and anti abuse of some other party.

Maybe something like "data use oriented toward protecting the user's safety and protecting the user from abuse" could be presumed appropriate?

**Comment by sandandsnow** [comment]
Note: there is also the risk that features designed for anti-abuse could be used for other purposes. Once a capability exists, it can be hard to ensure it only gets used for good purposes (e.g. fingerprinting).
