### ISSUE TITLE
Rewrite or drop the FIPs section

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#87]
Reading https://bobgellman.com/rg-docs/rg-FIPShistory.pdf, the [1973 FIPs memo](https://aspe.hhs.gov/reports/records-computers-rights-citizens), and the [1980 and 2013 OECD privacy guidelines](https://www.oecd.org/digital/ieconomy/privacy-guidelines.htm), it seems clear that the actual FIPs require much more than just "transparency and choice", as https://w3ctag.github.io/privacy-principles/#dfn-fair-information-practices implies. For example, the 1973 memo says "There must be a way for an individual to find out what information about him is in a record and how it is used.", which is only just now being enacted into law in an enforceable way.

There's a useful statement in this section that purely-procedural requirements are insufficient to support people's autonomy, especially in the presence of power imbalances, but we shouldn't mischaracterize the FIPs in order to make that point.

**Comment by darobin** [comment]
The FIPs have varied across time and implementation, and I'm not necessarily against rewriting, but I would like to understand which specific aspects you see as going significantly beyond T&C. The example you give is specifically a transparency requirement so it doesn't feel like a strong counter-example!

**Comment by sandandsnow** [comment]
Reflecting on Jeffrey's question about including the text regarding the FIPs, I am wondering how much to keep as some is arguably background. My sense is the key point we want to make is that having autonomy and control are aspects of individual's privacy. Perhaps we could consider distilling this section and including the origins and sources for the right (or other entitlement) to autonomy and control in footnotes or other notes?

**Comment by darobin** [comment]
I've moved much of the FIPs section into [Privacy Labour](https://pr-preview.s3.amazonaws.com/w3ctag/privacy-principles/pull/102.html#privacy-labour). I've made it more about self-governing, procedural regimes, how they impact labour and autonomy.

I don't know if that's enough — let me know!

**Comment by darobin** [comment]
This seems addressed.
