### ISSUE TITLE
Expand the "related documents" section

### ISSUE THREAD

**Issue by dmarti** [w3ctag/privacy-principles#9]
This is related to #7 -- include something about each document linked to in the "related documents" section, so that a reader who is looking for something better covered in one of those can find it, and so that new readers will understand the difference between this document and the others.

**Comment by torgo** [comment]
Maybe this is a dup of #7 given what we just discussed regarding a "what this doc is and what it's not" section?

**Comment by dmarti** [comment]
Duplicate of #7
